### ISSUE TITLE
reproduce results

### ISSUE THREAD

**Issue by songdejia** [MegviiDetection/video_analyst#24] opened 2020-03-05 02:56 UTC
Can we directly reproduce the results in paper without any further parameter fine-tune?

**Comment by MARMOTatZJU** [comment] 2020-03-05 07:45
For GOT-10k, yes. See [stability](https://github.com/MegviiDetection/video_analyst/blob/dev/docs/TRAINING.md) section in dev branch (it will be soon merged into the master branch). For our four released experiments, we reproduce them on four different "machines" and the fluctuation of performance seems reasonable (at least more reasonable than VOT).

For VOT, however, due to its _restart mechanism_, the result is very sensitive to hyper-parameters (hp). You need to either perform hp-search or train multiple times (so that the default hp meats the trained model). Based on our empirical observation, we recommend conducting further experiments on GOT for reasons of stability.

We are currently working to transplant our code from the internal base to the public base. Since it is easier to download TrackingNet than Youtube-BB, we plan to release the experiment on VOT with TrackingNet instead of Youtube-BB (priorly, we estimate little difference in performance by doing so).

**Closed** 2020-03-08 16:00 UTC
