### ISSUE TITLE
Training interruption

### ISSUE THREAD

**Issue by makalo** [MegviiDetection/video_analyst#25] opened 2020-03-06 04:57 UTC
When I train this model, the training process will be interrupted without any reason, but there is no error message. I don't know if you have this problem during your training. I haven't changed the training code, and the environment is configured according to README.

**Comment by lzx1413** [comment] 2020-03-06 06:29
1. Does this problem occur every  time of training?
2. can you supply some information such as training log and the log in snapshot/logs/data.log

**Comment by MARMOTatZJU** [comment] 2020-03-06 06:49
@makalo Could you please provide the Python Traceback (printed information whe interrupt) of the program so that we can try to figure out the cause and fix it for you?

**Comment by makalo** [comment] 2020-03-06 07:01
1.This problem does not occur in every epoch, it seems to be random.
2.Because I download the code and environment again, the previous log was lost. I will run the new training again. I will provide log and Python Traceback  later. Thank you

**Comment by makalo** [comment] 2020-03-06 07:49
Here are log and Traceback:

[data.log](https://github.com/MegviiDetection/video_analyst/files/4297127/data.log)


[Traceback.txt](https://github.com/MegviiDetection/video_analyst/files/4297130/Traceb

ack.txt)

**Comment by makalo** [comment] 2020-03-06 07:52
Here are log and Traceback:
[data.log](https://github.com/MegviiDetection/video_analyst/files/4297138/data.log)
[Traceback.txt](https://github.com/MegviiDetection/video_analyst/files/4297142/Traceback.txt)

**Comment by MARMOTatZJU** [comment] 2020-03-06 10:03
@makalo
In short, this is probably an issue related to the memory size.

As traced back, the shared memory may be used up due to limited memory size on your machine. Currently, we launch 32 workers to load data (see _num_workers in our .yaml files_) and this may consume memory of a size beyond your hardware resources.

You can try either of the following solutions (decreasingly ordered by priority):
* set _num_workers_ to a smaller number e.g. 16 or 8;
  * this will slow the training, but it may fix your _out of memory_  issue
* in _videoanalyst/data/builder.py_, L56, set _pin_memory_ to False (this has been parametrized into .yaml in our internal branch and we will soon perform a merge into the master branch);
* run training with larger memory (may not practical for you);

We are already aware of the issue of dataloader broken during training. We plan to provide a more robust version of dataloader (e.g. catch exception and handle those able to be solved by a quick fix) in our further release.

Separately, you can run the following script to monitor the shared memory usage in another terminal window during training.
```Bash
while true; do df -h | grep sh; sleep 10; done
```

**Comment by MARMOTatZJU** [comment] 2020-03-13 09:30
@makalo
Did our suggestion help? 
If so, can we close this issue?

**Comment by MARMOTatZJU** [comment] 2020-03-26 07:14
Issue closed as no further comment after nearly two weeks. Feel free to reopen it if you are still stucked by thgis interruption problem.

**Closed by MARMOTatZJU** 2020-03-26 07:14 UTC
